### ISSUE TITLE
How to get the Luna16 dataset?

### ISSUE THREAD

**Issue by DaLei001** [taki0112/CASED-Tensorflow#3]
I'm not join the LUNA16 challenge, Could I get the LUNA16 dataset and the tutorials? and how?
If you see this, tell me the answer please. Thank you!

**Comment by taki0112** [comment]
[here](https://luna16.grand-challenge.org/Download/)

**Comment by DaLei001** [comment]
@taki0112 This page can only be viewed by participants of this project, but I am not.

**Comment by taki0112** [comment]
You do not have to join LUNA16.
Just register and download.
